version: 2.1

jobs:
  job1:
    docker:
      - image: cimg/base:stable
    steps:
      - name: "Say hello"
        run: |
          echo Hello, World! $test1
        with:
          test1: ["test1", "test2", "test3"]

  job2:
    docker:
      - image: cimg/base:stable
    steps:
      - name: "Say hello"
        run: |
          echo Hello, World! $test1
        with:
          test1: ["test1", "test2", "test3"]

workflows:
  version: 2
  say-hello-workflow:
    jobs:
      - job1
      - job2
